### PR TITLE
Add eidos documentation

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Until the web page is generated, a reasonable view of the formatted document can be had at https://github.com/WorldModelers/CorpusIngestionAndAssembly/blob/kwalcock/eidosDocs/docs/eidos.md.

**Comment by MihaiSurdeanu** [comment]
Thanks! I'll take a look soon.

**Comment by MihaiSurdeanu** [comment]
Beautiful, thanks @kwalcock !

One comment: the W1, W2, ... symlinks seem broken. I get a 404 when I click on them. Is this because the doc page hasn't been deployed yet?

**Comment by kwalcock** [comment]
I *think* they will work on the published web page.  I will double check and repair if not.

**Comment by kwalcock** [comment]
I do need to merge the latest changes into master.  The link to docker-compose-eidos2.yml will not work until then.

**Pull request merged**
