### PR TITLE
Dart initial docs

### PR DESCRIPTION
**Pull request by johnhungerford**

### CODE REVIEW

**Comment by bgyori** [comment]
This looks good to me!

**Comment by kwalcock** [comment]
Thanks, @johnhungerford, for being the first and for organizing images.  I *think* this should simply show up at https://worldmodelers.com/CorpusIngestionAndAssembly/dart.html after the PR has been merged.  Would @bgyori like to do the honors?

**Comment by kwalcock** [comment]
The pages haven't been generated yet.  If it takes too much longer I will start looking for errors.

**Comment by bgyori** [comment]
I was just looking into that as well. The issue was that under settings, the pages were set up to build from the `documentation` branch, so I switched it over to `main`.

**Comment by bgyori** [comment]
Based on the rendering at https://worldmodelers.com/CorpusIngestionAndAssembly/dart.html, we might want to limit the size of some of the screenshots.

**Comment by kwalcock** [comment]
Thanks, Ben.  I had forgotten about the branch thing.  There was a reason, but not a good one, for that, so :-)

**Comment by johnhungerford** [comment]
I see that it's up now. Thanks! @bgyori I'll see if I can make the images format better

**Comment by kwalcock** [comment]
@johnhungerford, I noticed some links to ??? and point it out in case some automated process went awry or we need to figure out how to link to other nearby pages, etc.  Probably the links are forthcoming, though.

**Comment by johnhungerford** [comment]
@kwalcock sorry I never got back to you on this: yes, I still have to work out those links -- I figured it's better to have something incomplete up then wait for everything to be complete.

**Pull request merged**
