### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chanys**

### CODE REVIEW

**Comment by chanys** [comment]
Not exactly sure if I have write access to this. Assigning to @kwalcock to help merge. Thanks!

**Comment by kwalcock** [comment]
No problem.  If it becomes a problem, we can look into the repo or organization configuration.

**Comment by chanys** [comment]
@kwalcock , I was trying to revised the README and do a push today, but met with the following error:
```
ERROR: Permission to WorldModelers/CorpusIngestionAndAssembly.git denied to chanys.
```

Can you please help to see what's the issue? Do I need to be added as a member to the repo? Not sure why I could do this 2 weeks ago, but now can't. Thanks.

**Comment by kwalcock** [comment]
It may be that you can't write directly to master, but have to make a PR first and let someone else press the merge button.  I'll check on the perms.  Nothing has been changed recently.

**Comment by kwalcock** [comment]
@chanys, I added write access.  Maybe it will help.

**Pull request merged**
